language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - composer install --prefer-source --no-interaction --dev
  - mysql -e 'create database gzero-tests;'

script:
  - ./vendor/bin/phpmd src/ text phpmd.xml
  - ./vendor/bin/phpcs --standard=ruleset.xml src/ -n # -n no warnings
  - php vendor/phpunit/phpunit/phpunit --exclude-group ignore --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
